const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const root = path.resolve(__dirname, '..');
const read = file => fs.readFileSync(path.join(root, file), 'utf8');

const clientApp = read('pages/client/client-app.js');
const clientIndex = read('pages/client/index.html');
const clientCss = read('pages/client/client.css');
const orderCart = read('pages/client/order-cart.js');
const crmApp = read('js/app.js');
const crmClients = read('pages/clients.html');
const receiptSql = read('sql/storage_receipts.sql');

assert.match(clientApp, /name="ordMethod" value="online"/);
assert.match(clientApp, /name="ordMethod" value="card_transfer"/);
assert.match(clientApp, /id="ordReceipt"/);
assert.match(clientApp, /Прикрепи чек перевода/);
assert.match(clientApp, /async function uploadReceipt\(file\)/);
assert.match(clientApp, /storage\/v1\/object\/receipts/);
assert.match(clientApp, /storage:\/\/receipts\//);
assert.match(clientApp, /storage\/v1\/object\/sign\/receipts/);
assert.doesNotMatch(clientApp, /return `\$\{_url\(\)\}\/storage\/v1\/object\/public\/receipts/);
assert.match(clientApp, /receipt upload failed/);
assert.match(clientApp, /unexpected order submit error/);
assert.match(clientApp, /manualTransferDiscount/);
assert.match(clientCss, /\.cli-req-row/);
assert.match(crmApp, /manualTransferDiscount:\s*300/);
assert.match(crmApp, /requisites:\s*\(requisites/);
assert.match(clientApp, /if \(!tariffs\.length\)/);
assert.match(clientApp, /const PAYMENTS_API = 'https:\/\/mentori\.tech\/api\/payments'/);
assert.match(clientApp, /startPayment\(order\.id, btn, result\)/);
assert.match(clientApp, /Prefer': 'return=representation'/);
assert.match(clientApp, /data-pay-order/);
assert.match(clientIndex, /order-cart\.js/);
assert.match(clientApp, /order_type: 'multi_order'/);
assert.match(clientApp, /Добавить пакет для другой анкеты/);
assert.match(orderCart, /source\.fullOnly === true/);
assert.match(clientApp, /if \(tariffChanged\) qtyInput\.value = qtyInput\.min/);
assert.match(clientApp, /submit\.disabled = hasInvalidQuantity/);
assert.match(clientApp, /cart\.validateQuantity\(tariff, row\.querySelector/);
assert.doesNotMatch(clientApp, /Number\(qtyInput\.value\) < Number\(qtyInput\.min\)\) qtyInput\.value/);
assert.match(clientCss, /cli-cart-control__error/);
assert.match(crmApp, /privateTariffs\.concat\(paymentTariffs\)/);
assert.doesNotMatch(clientApp, /id="ordSubmit">Я оплатил|id="remainSubmit">Я оплатил/);
assert.match(crmClients, /manualTransfer && !!o\.receipt_url/);
assert.match(crmClients, /\/manual-confirm/);
assert.match(crmClients, /data-cancel-online/);
assert.match(crmClients, /\/orders\/cancel/);
assert.match(crmClients, /const canCancelOnline = o\.status === 'new' && onlinePayment && !onlinePaid && !onlineCanceled/);
assert.match(crmClients, /const canDelete = !onlinePayment && !\(manualTransfer && o\.status === 'confirmed'\)/);
assert.match(crmClients, /const canReject = o\.status === 'new' && !onlinePayment/);
assert.match(receiptSql, /values \('receipts','receipts', false/);
assert.match(receiptSql, /app_metadata' ->> 'role'\) = 'owner'/);
assert.match(receiptSql, /split_part\(name, '\/', 1\) = auth\.uid\(\)::text/);

console.log('client payment methods and requisites: OK');
