-- Canonical outreach schedule shared by the CRM and client cabinets.
-- Each remaining outreach is a separate slot, so the seven-per-day limit is
-- enforced atomically on the server even when several clients act at once.

begin;

create table if not exists public.client_outreach_slots (
  id bigint generated by default as identity primary key,
  client_email text,
  mentor_id text not null,
  anketa_code text,
  anketa_name text,
  scheduled_date date not null,
  slot_status text not null default 'scheduled'
    check (slot_status in ('scheduled', 'completed', 'cancelled')),
  source text not null default 'staff',
  seed_key text unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  completed_at timestamptz,
  cancelled_at timestamptz,
  changed_by text
);

create index if not exists client_outreach_slots_date_idx
  on public.client_outreach_slots (scheduled_date, id)
  where slot_status = 'scheduled';
create index if not exists client_outreach_slots_client_idx
  on public.client_outreach_slots (client_email, mentor_id, slot_status, scheduled_date);
create index if not exists client_outreach_slots_mentor_idx
  on public.client_outreach_slots (mentor_id, slot_status, scheduled_date);

alter table public.client_outreach_slots enable row level security;

drop policy if exists client_outreach_slots_client_select
  on public.client_outreach_slots;
create policy client_outreach_slots_client_select
  on public.client_outreach_slots
  for select to authenticated
  using (
    client_email = lower(coalesce(auth.jwt() ->> 'email', ''))
  );

drop policy if exists client_outreach_slots_staff_select
  on public.client_outreach_slots;
create policy client_outreach_slots_staff_select
  on public.client_outreach_slots
  for select to authenticated
  using (
    coalesce(auth.jwt() -> 'app_metadata' ->> 'role', '') in ('owner', 'team')
  );

grant select on public.client_outreach_slots to authenticated;
grant all on public.client_outreach_slots to service_role;
grant usage, select on sequence public.client_outreach_slots_id_seq to service_role;

-- Seed exact remaining plans from the RLS snapshots. A deterministic seed key
-- makes the migration idempotent.
insert into public.client_outreach_slots (
  client_email, mentor_id, anketa_code, anketa_name, scheduled_date,
  slot_status, source, seed_key, changed_by
)
select
  lower(snapshot.email),
  anketa ->> 'mentorId',
  anketa ->> 'code',
  anketa ->> 'name',
  (slot ->> 'date')::date,
  'scheduled',
  'snapshot_seed',
  'snapshot:' || lower(snapshot.email) || ':' || (anketa ->> 'mentorId') || ':'
    || (slot ->> 'date') || ':' || ordinal::text,
  'migration'
from public.client_snapshots snapshot
cross join lateral jsonb_array_elements(
  coalesce(snapshot.payload -> 'anketas', '[]'::jsonb)
) anketa
cross join lateral jsonb_array_elements(
  coalesce(anketa -> 'schedule', '[]'::jsonb)
) slot
cross join lateral generate_series(
  1,
  greatest(0, coalesce((slot ->> 'count')::int, 0))
) ordinal
where coalesce(anketa ->> 'mentorId', '') <> ''
  and coalesce(slot ->> 'date', '') ~ '^\d{4}-\d{2}-\d{2}$'
on conflict (seed_key) do nothing;

-- Keep plans of CRM clients who do not have a client cabinet yet. They count
-- towards the common daily capacity but are invisible to portal users.
with state as (
  select data from public.crm_state where id = 'main'
), snapshot_codes as (
  select distinct lower(regexp_replace(
    coalesce(anketa ->> 'code', ''), '[[:space:]-]+', '', 'g'
  )) as code
  from public.client_snapshots snapshot
  cross join lateral jsonb_array_elements(
    coalesce(snapshot.payload -> 'anketas', '[]'::jsonb)
  ) anketa
), legacy_clients as (
  select
    client,
    lower(regexp_replace(
      coalesce(client ->> 'code', ''), '[[:space:]-]+', '', 'g'
    )) as code
  from state
  cross join lateral jsonb_array_elements(coalesce(data -> 'clients', '[]'::jsonb)) client
), mentors as (
  select
    mentor,
    lower(regexp_replace(
      coalesce(mentor ->> 'code', ''), '[[:space:]-]+', '', 'g'
    )) as code
  from state
  cross join lateral jsonb_array_elements(coalesce(data -> 'mentors', '[]'::jsonb)) mentor
)
insert into public.client_outreach_slots (
  client_email, mentor_id, anketa_code, anketa_name, scheduled_date,
  slot_status, source, seed_key, changed_by
)
select
  null,
  mentors.mentor ->> 'id',
  legacy_clients.client ->> 'code',
  legacy_clients.client ->> 'name',
  (slot ->> 'date')::date,
  'scheduled',
  'legacy_seed',
  'legacy:' || (mentors.mentor ->> 'id') || ':' || (slot ->> 'date') || ':' || ordinal::text,
  'migration'
from legacy_clients
join mentors using (code)
cross join lateral jsonb_array_elements(
  coalesce(legacy_clients.client -> 'schedule', '[]'::jsonb)
) slot
cross join lateral generate_series(
  1,
  greatest(0, coalesce((slot ->> 'count')::int, 0))
) ordinal
where legacy_clients.code <> ''
  and not exists (select 1 from snapshot_codes where snapshot_codes.code = legacy_clients.code)
  and coalesce(slot ->> 'date', '') ~ '^\d{4}-\d{2}-\d{2}$'
on conflict (seed_key) do nothing;

create or replace function public.manage_client_outreach_slot(
  p_action text,
  p_slot_id bigint default null,
  p_mentor_id text default null,
  p_target_date date default null
)
returns public.client_outreach_slots
language plpgsql
security definer
set search_path = public
as $$
declare
  caller_email text := lower(coalesce(auth.jwt() ->> 'email', ''));
  caller_app_role text := coalesce(auth.jwt() -> 'app_metadata' ->> 'role', '');
  action_name text := lower(btrim(coalesce(p_action, '')));
  snapshot_payload jsonb;
  anketa jsonb;
  slot_row public.client_outreach_slots;
  old_date date;
  ordered_count int := 0;
  done_count int := 0;
  work_count int := 0;
  max_slots int := 0;
  current_slots int := 0;
  used_on_target int := 0;
  msg text;
begin
  if auth.role() <> 'authenticated'
     or caller_app_role <> 'client'
     or caller_email = '' then
    raise exception 'AUTH_REQUIRED' using errcode = '42501';
  end if;
  if action_name not in ('add', 'move', 'cancel') then
    raise exception 'ACTION_REQUIRED' using errcode = '22023';
  end if;

  if action_name in ('add', 'move') then
    if p_target_date is null
       or p_target_date < current_date
       or p_target_date > current_date + 180 then
      raise exception 'DATE_OUT_OF_RANGE' using errcode = '22023';
    end if;
    perform pg_advisory_xact_lock(hashtext('outreach:' || p_target_date::text));
  end if;

  select payload into snapshot_payload
  from public.client_snapshots
  where email = caller_email;
  if snapshot_payload is null then
    raise exception 'SNAPSHOT_NOT_FOUND' using errcode = 'P0002';
  end if;

  if action_name = 'add' then
    if coalesce(btrim(p_mentor_id), '') = '' then
      raise exception 'ANKETA_REQUIRED' using errcode = '22023';
    end if;
    -- Two parallel requests for different dates must not both consume the
    -- last review available in the same package.
    perform pg_advisory_xact_lock(hashtext(
      'outreach-client:' || caller_email || ':' || p_mentor_id
    ));
    select item into anketa
    from jsonb_array_elements(coalesce(snapshot_payload -> 'anketas', '[]'::jsonb)) item
    where item ->> 'mentorId' = p_mentor_id
    limit 1;
    if anketa is null then
      raise exception 'ANKETA_NOT_FOUND' using errcode = '42501';
    end if;

    ordered_count := greatest(0, coalesce((anketa ->> 'ordered')::int, 0));
    done_count := greatest(0, coalesce((anketa ->> 'done')::int, 0));
    select count(*)::int into work_count
    from jsonb_array_elements(coalesce(anketa -> 'statuses', '[]'::jsonb)) status_item
    where status_item ->> 'status' not in ('📋 Запланировано', '🎯 Готов');
    max_slots := greatest(0, ordered_count - done_count - work_count);

    select count(*)::int into current_slots
    from public.client_outreach_slots
    where client_email = caller_email
      and mentor_id = p_mentor_id
      and slot_status = 'scheduled';
    if current_slots >= max_slots then
      raise exception 'NO_AVAILABLE_OUTREACH' using errcode = 'P0001';
    end if;

    select count(*)::int into used_on_target
    from public.client_outreach_slots
    where scheduled_date = p_target_date and slot_status = 'scheduled';
    if used_on_target >= 7 then
      raise exception 'DAY_FULL' using errcode = 'P0001';
    end if;

    insert into public.client_outreach_slots (
      client_email, mentor_id, anketa_code, anketa_name, scheduled_date,
      slot_status, source, changed_by
    ) values (
      caller_email, p_mentor_id, anketa ->> 'code', anketa ->> 'name', p_target_date,
      'scheduled', 'client', caller_email
    ) returning * into slot_row;
    msg := '📅 Клиент запланировал отклик' || E'\n'
        || '👤 ' || coalesce(slot_row.anketa_code, '—') || ' · '
        || coalesce(slot_row.anketa_name, caller_email) || E'\n'
        || 'Дата: ' || to_char(slot_row.scheduled_date, 'DD.MM.YYYY');
  else
    select * into slot_row
    from public.client_outreach_slots
    where id = p_slot_id
      and client_email = caller_email
      and slot_status = 'scheduled'
    for update;
    if slot_row.id is null then
      raise exception 'SLOT_NOT_FOUND' using errcode = 'P0002';
    end if;
    old_date := slot_row.scheduled_date;

    if action_name = 'move' then
      if p_target_date = old_date then return slot_row; end if;
      select count(*)::int into used_on_target
      from public.client_outreach_slots
      where scheduled_date = p_target_date
        and slot_status = 'scheduled'
        and id <> slot_row.id;
      if used_on_target >= 7 then
        raise exception 'DAY_FULL' using errcode = 'P0001';
      end if;
      update public.client_outreach_slots
      set scheduled_date = p_target_date,
          updated_at = now(),
          changed_by = caller_email
      where id = slot_row.id
      returning * into slot_row;
      msg := '🔄 Клиент перенёс отклик' || E'\n'
          || '👤 ' || coalesce(slot_row.anketa_code, '—') || ' · '
          || coalesce(slot_row.anketa_name, caller_email) || E'\n'
          || to_char(old_date, 'DD.MM.YYYY') || ' → '
          || to_char(slot_row.scheduled_date, 'DD.MM.YYYY');
    else
      update public.client_outreach_slots
      set slot_status = 'cancelled',
          cancelled_at = now(),
          updated_at = now(),
          changed_by = caller_email
      where id = slot_row.id
      returning * into slot_row;
      msg := '❌ Клиент отменил запланированный отклик' || E'\n'
          || '👤 ' || coalesce(slot_row.anketa_code, '—') || ' · '
          || coalesce(slot_row.anketa_name, caller_email) || E'\n'
          || 'Был запланирован: ' || to_char(old_date, 'DD.MM.YYYY');
    end if;
  end if;

  insert into public.notification_outbox (
    telegram_chat_id, kind, message, status, mentor_id, client_email
  ) values (
    6876234451, 'client_outreach_schedule', msg, 'pending',
    slot_row.mentor_id, caller_email
  );
  return slot_row;
end;
$$;

revoke all on function public.manage_client_outreach_slot(text, bigint, text, date) from public;
grant execute on function public.manage_client_outreach_slot(text, bigint, text, date) to authenticated;

create or replace function public.get_client_outreach_calendar(
  p_from date,
  p_to date
)
returns table (
  schedule_date date,
  used_count int,
  capacity int,
  available_count int
)
language plpgsql
security definer
set search_path = public
as $$
declare
  caller_email text := lower(coalesce(auth.jwt() ->> 'email', ''));
  caller_app_role text := coalesce(auth.jwt() -> 'app_metadata' ->> 'role', '');
begin
  if auth.role() <> 'authenticated'
     or caller_app_role <> 'client'
     or caller_email = '' then
    raise exception 'AUTH_REQUIRED' using errcode = '42501';
  end if;
  if p_from is null or p_to is null or p_to < p_from or p_to > p_from + 62 then
    raise exception 'DATE_RANGE_INVALID' using errcode = '22023';
  end if;
  return query
  select
    day::date,
    count(slot.id)::int,
    7,
    greatest(0, 7 - count(slot.id)::int)
  from generate_series(p_from, p_to, interval '1 day') day
  left join public.client_outreach_slots slot
    on slot.scheduled_date = day::date and slot.slot_status = 'scheduled'
  group by day
  order by day;
end;
$$;

revoke all on function public.get_client_outreach_calendar(date, date) from public;
grant execute on function public.get_client_outreach_calendar(date, date) to authenticated;

create or replace function public.staff_adjust_outreach_slot(
  p_mentor_id text,
  p_date date,
  p_delta int
)
returns int
language plpgsql
security definer
set search_path = public
as $$
declare
  app_role text := coalesce(auth.jwt() -> 'app_metadata' ->> 'role', '');
  actor text := lower(coalesce(auth.jwt() ->> 'email', ''));
  owner_email text;
  anketa jsonb;
  target_id bigint;
  used_count int;
begin
  if auth.role() <> 'authenticated' or app_role not in ('owner', 'team') then
    raise exception 'AUTH_REQUIRED' using errcode = '42501';
  end if;
  if coalesce(btrim(p_mentor_id), '') = '' or p_date is null or p_delta not in (-1, 1) then
    raise exception 'INVALID_ARGUMENTS' using errcode = '22023';
  end if;
  perform pg_advisory_xact_lock(hashtext('outreach:' || p_date::text));

  if p_delta = 1 then
    select count(*)::int into used_count
    from public.client_outreach_slots
    where scheduled_date = p_date and slot_status = 'scheduled';
    if used_count >= 7 then
      raise exception 'DAY_FULL' using errcode = 'P0001';
    end if;
    select lower(snapshot.email), item into owner_email, anketa
    from public.client_snapshots snapshot
    cross join lateral jsonb_array_elements(
      coalesce(snapshot.payload -> 'anketas', '[]'::jsonb)
    ) item
    where item ->> 'mentorId' = p_mentor_id
    limit 1;
    insert into public.client_outreach_slots (
      client_email, mentor_id, anketa_code, anketa_name, scheduled_date,
      slot_status, source, changed_by
    ) values (
      owner_email, p_mentor_id, anketa ->> 'code', anketa ->> 'name', p_date,
      'scheduled', 'staff', actor
    );
  else
    select id into target_id
    from public.client_outreach_slots
    where mentor_id = p_mentor_id
      and scheduled_date = p_date
      and slot_status = 'scheduled'
    order by id desc
    limit 1
    for update;
    if target_id is not null then
      update public.client_outreach_slots
      set slot_status = 'cancelled', cancelled_at = now(), updated_at = now(), changed_by = actor
      where id = target_id;
    end if;
  end if;

  select count(*)::int into used_count
  from public.client_outreach_slots
  where mentor_id = p_mentor_id
    and scheduled_date = p_date
    and slot_status = 'scheduled';
  return used_count;
end;
$$;

revoke all on function public.staff_adjust_outreach_slot(text, date, int) from public;
grant execute on function public.staff_adjust_outreach_slot(text, date, int) to authenticated;

create or replace function public.staff_move_outreach_slot(
  p_mentor_id text,
  p_from date,
  p_to date
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  app_role text := coalesce(auth.jwt() -> 'app_metadata' ->> 'role', '');
  actor text := lower(coalesce(auth.jwt() ->> 'email', ''));
  target_id bigint;
  used_count int;
begin
  if auth.role() <> 'authenticated' or app_role not in ('owner', 'team') then
    raise exception 'AUTH_REQUIRED' using errcode = '42501';
  end if;
  if p_from is null or p_to is null or coalesce(btrim(p_mentor_id), '') = '' then
    raise exception 'INVALID_ARGUMENTS' using errcode = '22023';
  end if;
  if p_from = p_to then return true; end if;
  perform pg_advisory_xact_lock(hashtext('outreach:' || p_to::text));
  select count(*)::int into used_count
  from public.client_outreach_slots
  where scheduled_date = p_to and slot_status = 'scheduled';
  if used_count >= 7 then
    raise exception 'DAY_FULL' using errcode = 'P0001';
  end if;
  select id into target_id
  from public.client_outreach_slots
  where mentor_id = p_mentor_id
    and scheduled_date = p_from
    and slot_status = 'scheduled'
  order by id
  limit 1
  for update;
  if target_id is null then return false; end if;
  update public.client_outreach_slots
  set scheduled_date = p_to, updated_at = now(), changed_by = actor
  where id = target_id;
  return true;
end;
$$;

revoke all on function public.staff_move_outreach_slot(text, date, date) from public;
grant execute on function public.staff_move_outreach_slot(text, date, date) to authenticated;

create or replace function public.staff_clear_outreach_slots(p_mentor_id text)
returns int
language plpgsql
security definer
set search_path = public
as $$
declare
  app_role text := coalesce(auth.jwt() -> 'app_metadata' ->> 'role', '');
  actor text := lower(coalesce(auth.jwt() ->> 'email', ''));
  changed_count int;
begin
  if auth.role() <> 'authenticated' or app_role not in ('owner', 'team') then
    raise exception 'AUTH_REQUIRED' using errcode = '42501';
  end if;
  update public.client_outreach_slots
  set slot_status = 'cancelled', cancelled_at = now(), updated_at = now(), changed_by = actor
  where mentor_id = p_mentor_id and slot_status = 'scheduled';
  get diagnostics changed_count = row_count;
  return changed_count;
end;
$$;

revoke all on function public.staff_clear_outreach_slots(text) from public;
grant execute on function public.staff_clear_outreach_slots(text) to authenticated;

create or replace function public.staff_complete_outreach_slot(
  p_mentor_id text,
  p_date date
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  app_role text := coalesce(auth.jwt() -> 'app_metadata' ->> 'role', '');
  actor text := lower(coalesce(auth.jwt() ->> 'email', ''));
  target_id bigint;
begin
  if auth.role() <> 'authenticated' or app_role not in ('owner', 'team') then
    raise exception 'AUTH_REQUIRED' using errcode = '42501';
  end if;
  select id into target_id
  from public.client_outreach_slots
  where mentor_id = p_mentor_id
    and scheduled_date <= p_date
    and slot_status = 'scheduled'
  -- Prefer the slot planned for the actual start date. If work started late,
  -- close the oldest overdue slot instead of leaving it hanging forever.
  order by (scheduled_date = p_date) desc, scheduled_date, id
  limit 1
  for update;
  if target_id is null then return false; end if;
  update public.client_outreach_slots
  set slot_status = 'completed', completed_at = now(), updated_at = now(), changed_by = actor
  where id = target_id;
  return true;
end;
$$;

revoke all on function public.staff_complete_outreach_slot(text, date) from public;
grant execute on function public.staff_complete_outreach_slot(text, date) to authenticated;

notify pgrst, 'reload schema';

commit;
