-- Short-lived bearer sessions for the Telegram calendar Mini App. Raw tokens
-- are returned once to the bot and only SHA-256 digests are stored.

begin;

create table if not exists public.client_telegram_webapp_tokens (
  id bigint generated by default as identity primary key,
  token_hash bytea not null unique,
  portal_email text not null,
  member_id bigint not null references public.client_telegram_members(id) on delete cascade,
  telegram_chat_id bigint not null,
  created_at timestamptz not null default now(),
  expires_at timestamptz not null,
  last_used_at timestamptz,
  revoked_at timestamptz
);

create index if not exists client_telegram_webapp_tokens_member_idx
  on public.client_telegram_webapp_tokens (member_id, expires_at desc);

alter table public.client_telegram_webapp_tokens enable row level security;
revoke all on public.client_telegram_webapp_tokens from public, anon, authenticated;
grant all on public.client_telegram_webapp_tokens to service_role;
grant usage, select on sequence public.client_telegram_webapp_tokens_id_seq to service_role;

create or replace function public.issue_client_telegram_webapp_token(
  p_telegram_chat_id bigint
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_member public.client_telegram_members;
  v_token text;
  v_expires_at timestamptz := now() + interval '30 minutes';
begin
  if auth.role() <> 'service_role' then
    raise exception 'AUTH_REQUIRED' using errcode = '42501';
  end if;

  select * into v_member
  from public.client_telegram_members
  where telegram_chat_id = p_telegram_chat_id and is_active
  order by id
  limit 1;
  if v_member.id is null then
    return jsonb_build_object('ok', false, 'reason', 'CONTACT_NOT_FOUND');
  end if;

  v_token := encode(gen_random_bytes(32), 'hex');
  insert into public.client_telegram_webapp_tokens (
    token_hash, portal_email, member_id, telegram_chat_id, expires_at
  ) values (
    digest(v_token, 'sha256'), lower(v_member.portal_email),
    v_member.id, v_member.telegram_chat_id, v_expires_at
  );

  delete from public.client_telegram_webapp_tokens
  where expires_at < now() - interval '1 day';

  return jsonb_build_object(
    'ok', true,
    'token', v_token,
    'expires_at', v_expires_at
  );
end;
$$;

revoke all on function public.issue_client_telegram_webapp_token(bigint)
  from public, anon, authenticated;
grant execute on function public.issue_client_telegram_webapp_token(bigint)
  to service_role;

create or replace function public.client_telegram_webapp_context(p_token text)
returns table(portal_email text, member_id bigint, telegram_chat_id bigint)
language sql
security definer
set search_path = public
as $$
  select token.portal_email, token.member_id, token.telegram_chat_id
  from public.client_telegram_webapp_tokens token
  join public.client_telegram_members member on member.id = token.member_id
  where token.token_hash = digest(btrim(coalesce(p_token, '')), 'sha256')
    and token.revoked_at is null
    and token.expires_at > now()
    and member.is_active
  limit 1
$$;

revoke all on function public.client_telegram_webapp_context(text)
  from public, anon, authenticated;

create or replace function public.get_client_telegram_calendar(
  p_token text,
  p_from date,
  p_to date
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_portal text;
  v_member_id bigint;
  v_snapshot jsonb;
  v_from date := greatest(coalesce(p_from, current_date + 1), current_date + 1);
  v_to date := least(coalesce(p_to, current_date + 45), current_date + 90);
  v_anketas jsonb;
  v_calendar jsonb;
begin
  select ctx.portal_email, ctx.member_id
  into v_portal, v_member_id
  from public.client_telegram_webapp_context(p_token) ctx;
  if v_portal is null then
    raise exception 'TOKEN_INVALID_OR_EXPIRED' using errcode = '42501';
  end if;
  if v_to < v_from or v_to - v_from > 90 then
    raise exception 'DATE_RANGE_INVALID' using errcode = '22023';
  end if;

  select payload into v_snapshot
  from public.client_snapshots
  where lower(email) = lower(v_portal);
  if v_snapshot is null then
    raise exception 'PORTAL_NOT_FOUND' using errcode = 'P0002';
  end if;

  update public.client_telegram_webapp_tokens
  set last_used_at = now()
  where token_hash = digest(btrim(p_token), 'sha256');

  select coalesce(jsonb_agg(
    jsonb_build_object(
      'mentor_id', anketa ->> 'mentorId',
      'code', anketa ->> 'code',
      'name', anketa ->> 'name',
      'schedule_limit', greatest(0, coalesce(nullif(anketa ->> 'scheduleLimit', '')::int, 0)),
      'active_count', (
        select count(*)::int from public.client_outreach_slots slot
        where lower(slot.client_email) = lower(v_portal)
          and slot.mentor_id = anketa ->> 'mentorId'
          and slot.slot_status = 'scheduled'
          and slot.scheduled_date >= current_date
      ),
      'available_to_add', greatest(0,
        coalesce(nullif(anketa ->> 'scheduleLimit', '')::int, 0) - (
          select count(*)::int from public.client_outreach_slots slot
          where lower(slot.client_email) = lower(v_portal)
            and slot.mentor_id = anketa ->> 'mentorId'
            and slot.slot_status = 'scheduled'
            and slot.scheduled_date >= current_date
        )
      ),
      'slots', (
        select coalesce(jsonb_agg(jsonb_build_object(
          'id', slot.id,
          'scheduled_date', slot.scheduled_date,
          'slot_status', slot.slot_status
        ) order by slot.scheduled_date, slot.id), '[]'::jsonb)
        from public.client_outreach_slots slot
        where lower(slot.client_email) = lower(v_portal)
          and slot.mentor_id = anketa ->> 'mentorId'
          and slot.slot_status = 'scheduled'
          and slot.scheduled_date >= current_date
      )
    ) order by anketa ->> 'code'
  ), '[]'::jsonb)
  into v_anketas
  from jsonb_array_elements(coalesce(v_snapshot -> 'anketas', '[]'::jsonb)) anketa
  where coalesce((anketa ->> 'closed')::boolean, false) is false;

  select coalesce(jsonb_agg(jsonb_build_object(
    'date', day_value::date,
    'used_count', used_count,
    'capacity', 7,
    'available_count', greatest(0, 7 - used_count)
  ) order by day_value), '[]'::jsonb)
  into v_calendar
  from (
    select day_value, (
      select count(*)::int from public.client_outreach_slots slot
      where slot.scheduled_date = day_value::date
        and slot.slot_status = 'scheduled'
    ) as used_count
    from generate_series(v_from, v_to, interval '1 day') day_value
  ) days;

  return jsonb_build_object(
    'ok', true,
    'portal_email', v_portal,
    'client_name', coalesce(v_snapshot ->> 'name', ''),
    'minimum_date', (current_date + 1),
    'anketas', v_anketas,
    'calendar', v_calendar
  );
end;
$$;

revoke all on function public.get_client_telegram_calendar(text, date, date)
  from public;
grant execute on function public.get_client_telegram_calendar(text, date, date)
  to anon, authenticated;

create or replace function public.manage_client_telegram_outreach_slot(
  p_token text,
  p_action text,
  p_mentor_id text,
  p_slot_id bigint,
  p_target_date date
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_portal text;
  v_member_id bigint;
  v_snapshot jsonb;
  v_anketa jsonb;
  v_action text := lower(btrim(coalesce(p_action, '')));
  v_slot public.client_outreach_slots;
  v_used int;
  v_active int;
  v_limit int;
  v_message text;
begin
  select ctx.portal_email, ctx.member_id
  into v_portal, v_member_id
  from public.client_telegram_webapp_context(p_token) ctx;
  if v_portal is null then
    raise exception 'TOKEN_INVALID_OR_EXPIRED' using errcode = '42501';
  end if;
  if v_action not in ('add', 'move', 'cancel') then
    raise exception 'ACTION_INVALID' using errcode = '22023';
  end if;

  select payload into v_snapshot from public.client_snapshots
  where lower(email) = lower(v_portal);
  select item into v_anketa
  from jsonb_array_elements(coalesce(v_snapshot -> 'anketas', '[]'::jsonb)) item
  where item ->> 'mentorId' = p_mentor_id
    and coalesce((item ->> 'closed')::boolean, false) is false
  limit 1;
  if v_anketa is null then
    raise exception 'ANKETA_NOT_FOUND' using errcode = 'P0002';
  end if;

  if v_action in ('add', 'move') then
    if p_target_date is null or p_target_date < current_date + 1
       or p_target_date > current_date + 180 then
      raise exception 'DATE_OUT_OF_RANGE' using errcode = '22023';
    end if;
    perform pg_advisory_xact_lock(hashtextextended('client-outreach:' || p_target_date::text, 0));
    select count(*)::int into v_used
    from public.client_outreach_slots
    where scheduled_date = p_target_date and slot_status = 'scheduled'
      and (v_action <> 'move' or id <> p_slot_id);
    if v_used >= 7 then
      raise exception 'DAY_FULL' using errcode = 'P0001';
    end if;
  end if;

  if v_action = 'add' then
    v_limit := greatest(0, coalesce(nullif(v_anketa ->> 'scheduleLimit', '')::int, 0));
    select count(*)::int into v_active
    from public.client_outreach_slots
    where lower(client_email) = lower(v_portal)
      and mentor_id = p_mentor_id and slot_status = 'scheduled'
      and scheduled_date >= current_date;
    if v_active >= v_limit then
      raise exception 'SCHEDULE_LIMIT_REACHED' using errcode = 'P0001';
    end if;
    insert into public.client_outreach_slots (
      client_email, mentor_id, anketa_code, anketa_name, scheduled_date,
      slot_status, source, changed_by
    ) values (
      lower(v_portal), p_mentor_id, v_anketa ->> 'code', v_anketa ->> 'name',
      p_target_date, 'scheduled', 'client_telegram', 'telegram:' || v_member_id::text
    ) returning * into v_slot;
    v_message := '📅 Клиент запланировал отклик' || E'\n'
      || '👤 ' || coalesce(v_slot.anketa_code, '—') || ' · '
      || coalesce(v_slot.anketa_name, v_portal) || E'\n'
      || 'Дата: ' || to_char(v_slot.scheduled_date, 'DD.MM.YYYY');
  else
    select * into v_slot
    from public.client_outreach_slots
    where id = p_slot_id and lower(client_email) = lower(v_portal)
      and mentor_id = p_mentor_id and slot_status = 'scheduled'
    for update;
    if v_slot.id is null then
      raise exception 'SLOT_NOT_FOUND' using errcode = 'P0002';
    end if;
    if v_action = 'move' then
      update public.client_outreach_slots
      set scheduled_date = p_target_date, updated_at = now(),
          changed_by = 'telegram:' || v_member_id::text
      where id = v_slot.id returning * into v_slot;
      v_message := '🔄 Клиент перенёс отклик' || E'\n'
        || '👤 ' || coalesce(v_slot.anketa_code, '—') || ' · '
        || coalesce(v_slot.anketa_name, v_portal) || E'\n'
        || 'Новая дата: ' || to_char(v_slot.scheduled_date, 'DD.MM.YYYY');
    else
      update public.client_outreach_slots
      set slot_status = 'cancelled', cancelled_at = now(), updated_at = now(),
          changed_by = 'telegram:' || v_member_id::text
      where id = v_slot.id returning * into v_slot;
      v_message := '❌ Клиент отменил запланированный отклик' || E'\n'
        || '👤 ' || coalesce(v_slot.anketa_code, '—') || ' · '
        || coalesce(v_slot.anketa_name, v_portal) || E'\n'
        || 'Дата: ' || to_char(v_slot.scheduled_date, 'DD.MM.YYYY');
    end if;
  end if;

  update public.client_telegram_webapp_tokens
  set last_used_at = now()
  where token_hash = digest(btrim(p_token), 'sha256');

  insert into public.notification_outbox (
    telegram_chat_id, kind, message, status, mentor_id, client_email
  ) values (
    6876234451, 'client_outreach_schedule', v_message, 'pending',
    v_slot.mentor_id, v_portal
  );

  insert into public.client_telegram_audit (
    portal_email, member_id, event_name, actor, details
  ) values (
    v_portal, v_member_id, 'telegram_calendar_' || v_action,
    'telegram_webapp', jsonb_build_object(
      'slot_id', v_slot.id,
      'mentor_id', v_slot.mentor_id,
      'scheduled_date', v_slot.scheduled_date
    )
  );

  return jsonb_build_object(
    'ok', true,
    'slot_id', v_slot.id,
    'mentor_id', v_slot.mentor_id,
    'scheduled_date', v_slot.scheduled_date,
    'slot_status', v_slot.slot_status
  );
end;
$$;

revoke all on function public.manage_client_telegram_outreach_slot(
  text, text, text, bigint, date
) from public;
grant execute on function public.manage_client_telegram_outreach_slot(
  text, text, text, bigint, date
) to anon, authenticated;

notify pgrst, 'reload schema';

commit;
