-- Client referral links and one-review bonus for the invitee's first paid order.
-- Referral metadata is normalized and never written into crm_state.

begin;

create table if not exists public.client_referral_codes (
  portal_email text primary key,
  referral_code text not null unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (portal_email = lower(btrim(portal_email))),
  check (referral_code ~ '^[a-f0-9]{36}$')
);

create table if not exists public.client_referrals (
  id bigint generated by default as identity primary key,
  referral_code text not null references public.client_referral_codes(referral_code) on delete restrict,
  referrer_portal_email text not null,
  referrer_name text not null default '',
  telegram_user_id bigint not null unique,
  telegram_chat_id bigint not null,
  telegram_username text,
  telegram_first_name text,
  telegram_last_name text,
  referred_portal_email text,
  status text not null default 'pending',
  joined_at timestamptz not null default now(),
  linked_at timestamptz,
  last_seen_at timestamptz not null default now(),
  bonus_order_id bigint unique references public.client_orders(id) on delete set null,
  bonus_reserved_at timestamptz,
  bonus_applied_at timestamptz,
  updated_at timestamptz not null default now(),
  check (telegram_user_id > 0),
  check (telegram_chat_id > 0),
  check (status in ('pending', 'reserved', 'applied', 'rejected_self'))
);

create index if not exists client_referrals_referrer_idx
  on public.client_referrals (referrer_portal_email, joined_at desc);
create index if not exists client_referrals_referred_portal_idx
  on public.client_referrals (referred_portal_email, status)
  where referred_portal_email is not null;

alter table public.client_referral_codes enable row level security;
alter table public.client_referrals enable row level security;

drop policy if exists client_referral_codes_staff_select on public.client_referral_codes;
create policy client_referral_codes_staff_select
  on public.client_referral_codes for select to authenticated
  using (coalesce(auth.jwt() -> 'app_metadata' ->> 'role', '') in ('owner', 'team'));

drop policy if exists client_referrals_staff_select on public.client_referrals;
create policy client_referrals_staff_select
  on public.client_referrals for select to authenticated
  using (coalesce(auth.jwt() -> 'app_metadata' ->> 'role', '') in ('owner', 'team'));

revoke all on public.client_referral_codes, public.client_referrals from anon, authenticated;
grant select on public.client_referral_codes, public.client_referrals to authenticated;
grant all on public.client_referral_codes, public.client_referrals to service_role;
grant usage, select on sequence public.client_referrals_id_seq to service_role;

create or replace function public.get_my_client_referral_dashboard()
returns jsonb
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  v_portal text := public.current_client_portal_email();
  v_code text;
  v_name text := '';
  v_referrals jsonb := '[]'::jsonb;
begin
  if auth.role() <> 'authenticated'
     or coalesce(auth.jwt() -> 'app_metadata' ->> 'role', '') <> 'client'
     or v_portal = '' then
    raise exception 'AUTH_REQUIRED' using errcode = '42501';
  end if;

  perform pg_advisory_xact_lock(hashtext('client-referral-code:' || v_portal));
  select referral_code into v_code
  from public.client_referral_codes
  where portal_email = v_portal;

  if v_code is null then
    v_code := encode(gen_random_bytes(18), 'hex');
    insert into public.client_referral_codes (portal_email, referral_code)
    values (v_portal, v_code)
    on conflict (portal_email) do update set updated_at = now()
    returning referral_code into v_code;
  end if;

  select coalesce(snapshot.payload ->> 'name', '') into v_name
  from public.client_snapshots snapshot
  where lower(snapshot.email) = v_portal;

  select coalesce(jsonb_agg(jsonb_build_object(
    'id', referral.id,
    'username', referral.telegram_username,
    'first_name', referral.telegram_first_name,
    'last_name', referral.telegram_last_name,
    'joined_at', referral.joined_at,
    'linked_at', referral.linked_at,
    'status', referral.status,
    'bonus_applied_at', referral.bonus_applied_at
  ) order by referral.joined_at desc, referral.id desc), '[]'::jsonb)
  into v_referrals
  from public.client_referrals referral
  where referral.referrer_portal_email = v_portal;

  return jsonb_build_object(
    'referral_code', v_code,
    'bot_username', 'MentoriTG_bot',
    'cabinet_name', coalesce(v_name, ''),
    'referrals', v_referrals
  );
end;
$$;

revoke all on function public.get_my_client_referral_dashboard() from public, anon;
grant execute on function public.get_my_client_referral_dashboard() to authenticated;

create or replace function public.register_client_referral(
  p_referral_code text,
  p_telegram_user_id bigint,
  p_telegram_chat_id bigint,
  p_username text default null,
  p_first_name text default null,
  p_last_name text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_code public.client_referral_codes;
  v_existing public.client_referrals;
  v_referrer_name text := '';
begin
  if auth.role() <> 'service_role' then
    raise exception 'AUTH_REQUIRED' using errcode = '42501';
  end if;
  if coalesce(btrim(p_referral_code), '') = ''
     or p_telegram_user_id is null or p_telegram_user_id <= 0
     or p_telegram_chat_id is null or p_telegram_chat_id <= 0
     or p_telegram_user_id <> p_telegram_chat_id then
    raise exception 'INVALID_ARGUMENTS' using errcode = '22023';
  end if;

  select * into v_code
  from public.client_referral_codes
  where referral_code = lower(btrim(p_referral_code));
  if v_code.portal_email is null then
    return jsonb_build_object('ok', false, 'reason', 'REFERRAL_NOT_FOUND');
  end if;

  if exists (
    select 1 from public.client_telegram_members member
    where member.telegram_user_id = p_telegram_user_id
      and member.is_active
      and lower(member.portal_email) = v_code.portal_email
  ) then
    return jsonb_build_object('ok', false, 'reason', 'SELF_REFERRAL');
  end if;

  perform pg_advisory_xact_lock(hashtext('client-referral-user:' || p_telegram_user_id::text));
  select * into v_existing
  from public.client_referrals
  where telegram_user_id = p_telegram_user_id
  for update;

  select coalesce(snapshot.payload ->> 'name', '') into v_referrer_name
  from public.client_snapshots snapshot
  where lower(snapshot.email) = v_code.portal_email;

  if v_existing.id is not null then
    update public.client_referrals
    set telegram_chat_id = p_telegram_chat_id,
        telegram_username = nullif(lower(regexp_replace(coalesce(p_username, ''), '^@', '')), ''),
        telegram_first_name = nullif(btrim(p_first_name), ''),
        telegram_last_name = nullif(btrim(p_last_name), ''),
        last_seen_at = now(),
        updated_at = now()
    where id = v_existing.id;
    if v_existing.referrer_portal_email <> v_code.portal_email then
      return jsonb_build_object('ok', false, 'reason', 'REFERRAL_ALREADY_ATTRIBUTED');
    end if;
    update public.client_referrals referral
    set referred_portal_email = lower(member.portal_email),
        linked_at = coalesce(referral.linked_at, now()),
        updated_at = now()
    from public.client_telegram_members member
    where referral.id = v_existing.id
      and referral.status = 'pending'
      and member.telegram_user_id = p_telegram_user_id
      and member.is_active
      and lower(member.portal_email) <> v_code.portal_email;
    return jsonb_build_object(
      'ok', true,
      'already_attributed', true,
      'referrer_name', coalesce(nullif(v_referrer_name, ''), v_existing.referrer_name, 'клиента Mentori')
    );
  end if;

  insert into public.client_referrals (
    referral_code, referrer_portal_email, referrer_name,
    telegram_user_id, telegram_chat_id, telegram_username,
    telegram_first_name, telegram_last_name
  ) values (
    v_code.referral_code, v_code.portal_email, coalesce(v_referrer_name, ''),
    p_telegram_user_id, p_telegram_chat_id,
    nullif(lower(regexp_replace(coalesce(p_username, ''), '^@', '')), ''),
    nullif(btrim(p_first_name), ''), nullif(btrim(p_last_name), '')
  );

  update public.client_referrals referral
  set referred_portal_email = lower(member.portal_email),
      linked_at = coalesce(referral.linked_at, now()),
      updated_at = now()
  from public.client_telegram_members member
  where referral.telegram_user_id = p_telegram_user_id
    and referral.status = 'pending'
    and member.telegram_user_id = p_telegram_user_id
    and member.is_active
    and lower(member.portal_email) <> v_code.portal_email;

  return jsonb_build_object(
    'ok', true,
    'already_attributed', false,
    'referrer_name', coalesce(nullif(v_referrer_name, ''), 'клиента Mentori')
  );
end;
$$;

revoke all on function public.register_client_referral(text, bigint, bigint, text, text, text)
  from public, anon, authenticated;
grant execute on function public.register_client_referral(text, bigint, bigint, text, text, text)
  to service_role;

create or replace function public.link_client_referral_portal()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if not NEW.is_active then
    return NEW;
  end if;
  update public.client_referrals referral
  set referred_portal_email = case
        when referral.referrer_portal_email = lower(NEW.portal_email) then null
        else lower(NEW.portal_email)
      end,
      status = case
        when referral.referrer_portal_email = lower(NEW.portal_email) then 'rejected_self'
        else 'pending'
      end,
      linked_at = case
        when referral.referrer_portal_email = lower(NEW.portal_email) then null
        else coalesce(referral.linked_at, now())
      end,
      updated_at = now()
  where referral.telegram_user_id = NEW.telegram_user_id
    and referral.status in ('pending', 'rejected_self');
  return NEW;
end;
$$;

drop trigger if exists client_telegram_members_referral_link_trg
  on public.client_telegram_members;
create trigger client_telegram_members_referral_link_trg
  after insert or update of portal_email, is_active on public.client_telegram_members
  for each row execute function public.link_client_referral_portal();

create or replace function public.referral_bonus_actor_allowed()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select auth.role() = 'service_role'
    or (
      auth.role() = 'authenticated'
      and coalesce(auth.jwt() -> 'app_metadata' ->> 'role', '') in ('owner', 'team')
    )
    or session_user in ('postgres', 'mentori_payments');
$$;

revoke all on function public.referral_bonus_actor_allowed() from public, anon, authenticated;
grant execute on function public.referral_bonus_actor_allowed() to service_role;

create or replace function public.reserve_client_referral_bonus(p_order_id bigint)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_order public.client_orders;
  v_referral public.client_referrals;
  v_email text;
begin
  if not public.referral_bonus_actor_allowed() then
    raise exception 'AUTH_REQUIRED' using errcode = '42501';
  end if;

  select * into v_order from public.client_orders
  where id = p_order_id for update;
  if v_order.id is null then
    return jsonb_build_object('eligible', false, 'reason', 'ORDER_NOT_FOUND', 'bonus_qty', 0);
  end if;
  v_email := lower(btrim(coalesce(v_order.client_email, '')));
  if v_email = '' or v_order.status <> 'new'
     or coalesce(v_order.order_type, 'order') in ('remainder', 'package_item', 'referral_bonus')
     or coalesce(v_order.amount, 0) <= 0 then
    return jsonb_build_object('eligible', false, 'reason', 'ORDER_NOT_ELIGIBLE', 'bonus_qty', 0);
  end if;

  perform pg_advisory_xact_lock(hashtext('client-referral-bonus:' || v_email));
  select * into v_referral
  from public.client_referrals referral
  where lower(coalesce(referral.referred_portal_email, '')) = v_email
    and referral.status in ('pending', 'reserved', 'applied')
  order by referral.joined_at, referral.id
  limit 1
  for update;

  if v_referral.id is null then
    return jsonb_build_object('eligible', false, 'reason', 'REFERRAL_NOT_LINKED', 'bonus_qty', 0);
  end if;
  if v_referral.status = 'applied' then
    return jsonb_build_object('eligible', false, 'reason', 'BONUS_ALREADY_APPLIED', 'bonus_qty', 0);
  end if;
  if v_referral.status = 'reserved' then
    if v_referral.bonus_order_id = p_order_id then
      return jsonb_build_object('eligible', true, 'referral_id', v_referral.id, 'bonus_qty', 1);
    end if;
    return jsonb_build_object('eligible', false, 'reason', 'BONUS_ALREADY_RESERVED', 'bonus_qty', 0);
  end if;

  if exists (
    select 1 from public.client_orders previous
    where lower(coalesce(previous.client_email, '')) = v_email
      and previous.id <> v_order.id
      and previous.parent_order_id is null
      and previous.status = 'confirmed'
      and coalesce(previous.order_type, 'order') not in ('remainder', 'package_item', 'referral_bonus')
      and coalesce(previous.amount, 0) > 0
  ) then
    return jsonb_build_object('eligible', false, 'reason', 'NOT_FIRST_ORDER', 'bonus_qty', 0);
  end if;

  update public.client_referrals
  set status = 'reserved', bonus_order_id = p_order_id,
      bonus_reserved_at = now(), updated_at = now()
  where id = v_referral.id;

  return jsonb_build_object('eligible', true, 'referral_id', v_referral.id, 'bonus_qty', 1);
end;
$$;

revoke all on function public.reserve_client_referral_bonus(bigint) from public, anon;
grant execute on function public.reserve_client_referral_bonus(bigint) to authenticated, service_role;

create or replace function public.release_client_referral_bonus(p_order_id bigint)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  v_count int;
begin
  if not public.referral_bonus_actor_allowed() then
    raise exception 'AUTH_REQUIRED' using errcode = '42501';
  end if;
  update public.client_referrals
  set status = 'pending', bonus_order_id = null, bonus_reserved_at = null, updated_at = now()
  where bonus_order_id = p_order_id and status = 'reserved';
  get diagnostics v_count = row_count;
  return v_count > 0;
end;
$$;

revoke all on function public.release_client_referral_bonus(bigint) from public, anon;
grant execute on function public.release_client_referral_bonus(bigint) to authenticated, service_role;

create or replace function public.complete_client_referral_bonus(
  p_order_id bigint,
  p_anketa_code text,
  p_anketa_name text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_order public.client_orders;
  v_referral public.client_referrals;
  v_bonus_id bigint;
begin
  if not public.referral_bonus_actor_allowed() then
    raise exception 'AUTH_REQUIRED' using errcode = '42501';
  end if;
  if coalesce(btrim(p_anketa_code), '') = '' then
    raise exception 'ANKETA_REQUIRED' using errcode = '22023';
  end if;

  select * into v_order from public.client_orders
  where id = p_order_id for update;
  if v_order.id is null then
    raise exception 'ORDER_NOT_FOUND' using errcode = 'P0002';
  end if;

  select * into v_referral
  from public.client_referrals
  where bonus_order_id = p_order_id and status in ('reserved', 'applied')
  for update;
  if v_referral.id is null then
    return jsonb_build_object('ok', false, 'reason', 'BONUS_NOT_RESERVED');
  end if;

  insert into public.client_orders (
    parent_order_id, parent_item_id, client_email, client_name,
    anketa_code, anketa_name, is_new_anketa,
    tariff_name, tariff_price, qty, amount, pay_full, prepay_amount,
    remainder_status, order_type, comment,
    offer_agreed, offer_text, offer_version,
    personal_data_agreed, personal_data_consent_text,
    personal_data_consent_version, consent_user_agent,
    status, confirmed_at, created_by, payment_method, discount_amount,
    payment_provider, payment_id, payment_status,
    payment_environment, payment_created_at, payment_paid_at
  ) values (
    v_order.id, 'referral-bonus', v_order.client_email, v_order.client_name,
    btrim(p_anketa_code), coalesce(nullif(btrim(p_anketa_name), ''), btrim(p_anketa_code)), false,
    'Реферальный бонус', 0, 1, 0, true, 0,
    null, 'referral_bonus', '1 отзыв в подарок за первый заказ по рекомендации',
    v_order.offer_agreed, v_order.offer_text, v_order.offer_version,
    v_order.personal_data_agreed, v_order.personal_data_consent_text,
    v_order.personal_data_consent_version, v_order.consent_user_agent,
    'confirmed', coalesce(v_order.confirmed_at, now()), 'referral-program',
    coalesce(v_order.payment_method, 'online'), 0,
    v_order.payment_provider, v_order.payment_id, coalesce(v_order.payment_status, 'paid'),
    v_order.payment_environment, v_order.payment_created_at, coalesce(v_order.payment_paid_at, now())
  )
  on conflict (parent_order_id, parent_item_id)
    where parent_order_id is not null do update
  set anketa_code = excluded.anketa_code,
      anketa_name = excluded.anketa_name,
      confirmed_at = excluded.confirmed_at
  returning id into v_bonus_id;

  update public.client_referrals
  set status = 'applied', bonus_applied_at = coalesce(bonus_applied_at, now()), updated_at = now()
  where id = v_referral.id;

  return jsonb_build_object(
    'ok', true,
    'referral_id', v_referral.id,
    'bonus_order_id', v_bonus_id,
    'bonus_qty', 1
  );
end;
$$;

revoke all on function public.complete_client_referral_bonus(bigint, text, text)
  from public, anon;
grant execute on function public.complete_client_referral_bonus(bigint, text, text)
  to authenticated, service_role;

do $$
begin
  if exists (select 1 from pg_roles where rolname = 'mentori_payments') then
    execute 'grant select, insert, update on public.client_referrals to mentori_payments';
    execute 'grant select on public.client_referral_codes to mentori_payments';
    execute 'grant usage, select on sequence public.client_referrals_id_seq to mentori_payments';
    execute 'grant execute on function public.reserve_client_referral_bonus(bigint) to mentori_payments';
    execute 'grant execute on function public.release_client_referral_bonus(bigint) to mentori_payments';
    execute 'grant execute on function public.complete_client_referral_bonus(bigint, text, text) to mentori_payments';
  end if;
end;
$$;

notify pgrst, 'reload schema';

commit;
