-- Review text approval between the CRM owner and the client's primary
-- Telegram contact. Decisions are atomic and fully audited.

begin;

create table if not exists public.client_text_approval_requests (
  id bigint generated by default as identity primary key,
  portal_email text not null,
  mentor_id text,
  anketa_code text,
  anketa_name text,
  title text not null default 'Текст отзыва',
  body text not null,
  request_status text not null default 'pending'
    check (request_status in ('pending', 'approved', 'changes_requested', 'cancelled')),
  delivered_to_member_id bigint,
  delivered_to_telegram_user_id bigint,
  created_by text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  resolved_at timestamptz,
  resolved_by_member_id bigint,
  resolved_by_telegram_user_id bigint,
  resolved_by_label text,
  resolution_comment text,
  check (length(title) between 1 and 200),
  check (length(body) between 1 and 3000),
  check (length(coalesce(resolution_comment, '')) <= 1500)
);

create index if not exists client_text_approvals_portal_idx
  on public.client_text_approval_requests (portal_email, created_at desc);
create index if not exists client_text_approvals_pending_idx
  on public.client_text_approval_requests (created_at)
  where request_status = 'pending';

alter table public.client_text_approval_requests enable row level security;

drop policy if exists client_text_approvals_staff_select
  on public.client_text_approval_requests;
create policy client_text_approvals_staff_select
  on public.client_text_approval_requests for select to authenticated
  using (coalesce(auth.jwt() -> 'app_metadata' ->> 'role', '') in ('owner', 'team'));

drop policy if exists client_text_approvals_client_select
  on public.client_text_approval_requests;
create policy client_text_approvals_client_select
  on public.client_text_approval_requests for select to authenticated
  using (
    coalesce(auth.jwt() -> 'app_metadata' ->> 'role', '') = 'client'
    and lower(portal_email) = public.current_client_portal_email()
  );

revoke all on public.client_text_approval_requests from anon, authenticated;
grant select on public.client_text_approval_requests to authenticated;
grant all on public.client_text_approval_requests to service_role;
grant usage, select on sequence public.client_text_approval_requests_id_seq
  to service_role;

create or replace function public.create_client_text_approval(
  p_portal_email text,
  p_mentor_id text,
  p_title text,
  p_body text
)
returns public.client_text_approval_requests
language plpgsql
security definer
set search_path = public
as $$
declare
  v_role text := coalesce(auth.jwt() -> 'app_metadata' ->> 'role', '');
  v_portal text := lower(btrim(coalesce(p_portal_email, '')));
  v_snapshot jsonb;
  v_anketa jsonb;
  v_member public.client_telegram_members;
  v_request public.client_text_approval_requests;
  v_safe_title text;
  v_safe_body text;
  v_message text;
begin
  if auth.role() <> 'authenticated' or v_role <> 'owner' then
    raise exception 'AUTH_REQUIRED' using errcode = '42501';
  end if;
  if v_portal = '' or coalesce(btrim(p_body), '') = '' then
    raise exception 'INVALID_ARGUMENTS' using errcode = '22023';
  end if;
  if length(btrim(p_body)) > 3000 then
    raise exception 'TEXT_TOO_LONG' using errcode = '22023';
  end if;
  if length(coalesce(nullif(btrim(p_title), ''), 'Текст отзыва')) > 200 then
    raise exception 'TITLE_TOO_LONG' using errcode = '22023';
  end if;

  select payload into v_snapshot
  from public.client_snapshots
  where lower(email) = v_portal;
  if v_snapshot is null then
    raise exception 'PORTAL_NOT_FOUND' using errcode = 'P0002';
  end if;

  if coalesce(btrim(p_mentor_id), '') <> '' then
    select item into v_anketa
    from jsonb_array_elements(coalesce(v_snapshot -> 'anketas', '[]'::jsonb)) item
    where item ->> 'mentorId' = p_mentor_id
    limit 1;
    if v_anketa is null then
      raise exception 'ANKETA_NOT_FOUND' using errcode = 'P0002';
    end if;
  end if;

  select * into v_member
  from public.client_telegram_members
  where lower(portal_email) = v_portal
    and is_active and is_text_approver
  limit 1;
  if v_member.id is null then
    raise exception 'TEXT_APPROVER_NOT_LINKED' using errcode = 'P0001';
  end if;

  insert into public.client_text_approval_requests (
    portal_email, mentor_id, anketa_code, anketa_name,
    title, body, request_status,
    delivered_to_member_id, delivered_to_telegram_user_id,
    created_by
  ) values (
    v_portal, nullif(btrim(p_mentor_id), ''),
    v_anketa ->> 'code', v_anketa ->> 'name',
    coalesce(nullif(btrim(p_title), ''), 'Текст отзыва'),
    btrim(p_body), 'pending',
    v_member.id, v_member.telegram_user_id,
    lower(coalesce(auth.jwt() ->> 'email', 'owner'))
  ) returning * into v_request;

  v_safe_title := replace(replace(replace(v_request.title,
    '&', '&amp;'), '<', '&lt;'), '>', '&gt;');
  v_safe_body := replace(replace(replace(v_request.body,
    '&', '&amp;'), '<', '&lt;'), '>', '&gt;');
  v_message := '📝 <b>' || v_safe_title || '</b>' || E'\n'
    || case when coalesce(v_request.anketa_code, '') <> ''
      then 'Анкета: <b>'
        || replace(replace(replace(v_request.anketa_code, '&', '&amp;'), '<', '&lt;'), '>', '&gt;')
        || '</b>'
        || case when coalesce(v_request.anketa_name, '') <> ''
          then ' · ' || replace(replace(replace(v_request.anketa_name, '&', '&amp;'), '<', '&lt;'), '>', '&gt;')
          else '' end
        || E'\n\n'
      else E'\n'
    end
    || v_safe_body || E'\n\n'
    || 'Проверьте текст и выберите действие.';

  insert into public.notification_outbox (
    client_email, telegram_chat_id, telegram_username,
    kind, message, status, mentor_id, action_ref
  ) values (
    v_portal, v_member.telegram_chat_id, v_member.telegram_username,
    'client_text_approval', v_message, 'pending',
    v_request.mentor_id, v_request.id::text
  );

  insert into public.client_telegram_audit (
    portal_email, member_id, event_name, actor, details
  ) values (
    v_portal, v_member.id, 'text_approval_created',
    lower(coalesce(auth.jwt() ->> 'email', 'owner')),
    jsonb_build_object('request_id', v_request.id, 'mentor_id', v_request.mentor_id)
  );

  return v_request;
end;
$$;

revoke all on function public.create_client_text_approval(text, text, text, text)
  from public, anon;
grant execute on function public.create_client_text_approval(text, text, text, text)
  to authenticated;

create or replace function public.cancel_client_text_approval(p_request_id bigint)
returns public.client_text_approval_requests
language plpgsql
security definer
set search_path = public
as $$
declare
  v_request public.client_text_approval_requests;
begin
  if auth.role() <> 'authenticated'
     or coalesce(auth.jwt() -> 'app_metadata' ->> 'role', '') <> 'owner' then
    raise exception 'AUTH_REQUIRED' using errcode = '42501';
  end if;
  update public.client_text_approval_requests
  set request_status = 'cancelled', updated_at = now(), resolved_at = now(),
      resolved_by_label = 'Владелец CRM'
  where id = p_request_id and request_status = 'pending'
  returning * into v_request;
  if v_request.id is null then
    raise exception 'REQUEST_NOT_PENDING' using errcode = 'P0001';
  end if;
  return v_request;
end;
$$;

revoke all on function public.cancel_client_text_approval(bigint) from public, anon;
grant execute on function public.cancel_client_text_approval(bigint) to authenticated;

create or replace function public.resolve_client_text_approval(
  p_request_id bigint,
  p_decision text,
  p_telegram_user_id bigint,
  p_telegram_chat_id bigint,
  p_comment text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_decision text := lower(btrim(coalesce(p_decision, '')));
  v_request public.client_text_approval_requests;
  v_member public.client_telegram_members;
begin
  if auth.role() <> 'service_role' then
    raise exception 'AUTH_REQUIRED' using errcode = '42501';
  end if;
  if v_decision not in ('approved', 'changes_requested') then
    raise exception 'DECISION_INVALID' using errcode = '22023';
  end if;
  if v_decision = 'changes_requested' and coalesce(btrim(p_comment), '') = '' then
    raise exception 'COMMENT_REQUIRED' using errcode = '22023';
  end if;
  if length(coalesce(p_comment, '')) > 1500 then
    raise exception 'COMMENT_TOO_LONG' using errcode = '22023';
  end if;

  select * into v_request
  from public.client_text_approval_requests
  where id = p_request_id
  for update;
  if v_request.id is null then
    return jsonb_build_object('ok', false, 'reason', 'REQUEST_NOT_FOUND');
  end if;
  if v_request.request_status <> 'pending' then
    return jsonb_build_object(
      'ok', false,
      'reason', 'ALREADY_RESOLVED',
      'status', v_request.request_status,
      'resolved_by', v_request.resolved_by_label
    );
  end if;

  select * into v_member
  from public.client_telegram_members
  where telegram_user_id = p_telegram_user_id
    and telegram_chat_id = p_telegram_chat_id
    and lower(portal_email) = lower(v_request.portal_email)
    and is_active and is_text_approver
  for update;
  if v_member.id is null then
    raise exception 'TEXT_APPROVER_REQUIRED' using errcode = '42501';
  end if;

  update public.client_text_approval_requests
  set request_status = v_decision,
      updated_at = now(),
      resolved_at = now(),
      resolved_by_member_id = v_member.id,
      resolved_by_telegram_user_id = v_member.telegram_user_id,
      resolved_by_label = coalesce(v_member.contact_label,
        nullif(v_member.telegram_first_name, ''),
        nullif(v_member.telegram_username, ''), 'Контакт'),
      resolution_comment = nullif(btrim(p_comment), '')
  where id = v_request.id and request_status = 'pending'
  returning * into v_request;

  if v_request.id is null then
    return jsonb_build_object('ok', false, 'reason', 'ALREADY_RESOLVED');
  end if;

  insert into public.client_telegram_audit (
    portal_email, member_id, event_name, actor, details
  ) values (
    v_request.portal_email, v_member.id, 'text_approval_resolved',
    'telegram:' || v_member.telegram_user_id::text,
    jsonb_build_object('request_id', v_request.id, 'decision', v_decision)
  );

  return jsonb_build_object(
    'ok', true,
    'request_id', v_request.id,
    'status', v_request.request_status,
    'resolved_by', v_request.resolved_by_label
  );
end;
$$;

revoke all on function public.resolve_client_text_approval(bigint, text, bigint, bigint, text)
  from public, anon, authenticated;
grant execute on function public.resolve_client_text_approval(bigint, text, bigint, bigint, text)
  to service_role;

create or replace function public.notify_owner_text_approval_result()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  owner_chat bigint := 6876234451;
  v_comment text;
  v_message text;
begin
  if OLD.request_status <> 'pending'
     or NEW.request_status not in ('approved', 'changes_requested') then
    return NEW;
  end if;
  v_comment := replace(replace(replace(coalesce(NEW.resolution_comment, ''),
    '&', '&amp;'), '<', '&lt;'), '>', '&gt;');
  v_message := case when NEW.request_status = 'approved'
      then '✅ <b>Клиент согласовал текст</b>'
      else '✏️ <b>Клиент прислал правки по тексту</b>'
    end || E'\n'
    || 'Кабинет: ' || coalesce(NEW.portal_email, '—')
    || case when coalesce(NEW.anketa_code, '') <> ''
      then E'\nАнкета: ' || NEW.anketa_code
        || case when coalesce(NEW.anketa_name, '') <> '' then ' · ' || NEW.anketa_name else '' end
      else '' end
    || E'\nОтветил: ' || coalesce(NEW.resolved_by_label, 'контакт')
    || case when v_comment <> '' then E'\n\nКомментарий:\n' || v_comment else '' end;

  insert into public.notification_outbox (
    telegram_chat_id, kind, message, status,
    mentor_id, client_email, action_ref
  ) values (
    owner_chat, 'client_text_approval_result', v_message, 'pending',
    NEW.mentor_id, NEW.portal_email, NEW.id::text
  );
  return NEW;
end;
$$;

drop trigger if exists client_text_approval_result_notify_trg
  on public.client_text_approval_requests;
create trigger client_text_approval_result_notify_trg
  after update of request_status on public.client_text_approval_requests
  for each row execute function public.notify_owner_text_approval_result();

notify pgrst, 'reload schema';

commit;
