-- Client-selected publication dates.
-- The client writes only through a SECURITY DEFINER RPC that validates the
-- requested status against their RLS-protected client snapshot.

begin;

create table if not exists public.client_publication_requests (
  id bigint generated by default as identity primary key,
  client_email text not null,
  status_id text not null,
  mentor_id text not null,
  profile_id text not null,
  status_date date not null,
  anketa_code text,
  anketa_name text,
  account_name text,
  requested_date date not null,
  request_status text not null default 'pending'
    check (request_status in ('pending', 'accepted', 'rejected', 'cancelled')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  resolved_at timestamptz,
  resolved_by text,
  unique (client_email, status_id)
);

create index if not exists client_publication_requests_pending_date_idx
  on public.client_publication_requests (requested_date, created_at)
  where request_status = 'pending';

alter table public.client_publication_requests enable row level security;

drop policy if exists client_publication_requests_client_select
  on public.client_publication_requests;
create policy client_publication_requests_client_select
  on public.client_publication_requests
  for select to authenticated
  using (
    client_email = lower(coalesce(auth.jwt() ->> 'email', ''))
  );

drop policy if exists client_publication_requests_staff_select
  on public.client_publication_requests;
create policy client_publication_requests_staff_select
  on public.client_publication_requests
  for select to authenticated
  using (
    coalesce(auth.jwt() -> 'app_metadata' ->> 'role', '') in ('owner', 'team')
  );

drop policy if exists client_publication_requests_staff_update
  on public.client_publication_requests;
create policy client_publication_requests_staff_update
  on public.client_publication_requests
  for update to authenticated
  using (
    coalesce(auth.jwt() -> 'app_metadata' ->> 'role', '') in ('owner', 'team')
  )
  with check (
    coalesce(auth.jwt() -> 'app_metadata' ->> 'role', '') in ('owner', 'team')
  );

grant select, update on public.client_publication_requests to authenticated;
grant all on public.client_publication_requests to service_role;
grant usage, select on sequence public.client_publication_requests_id_seq to service_role;

create or replace function public.request_client_publication_date(
  p_status_id text,
  p_requested_date date
)
returns public.client_publication_requests
language plpgsql
security definer
set search_path = public
as $$
declare
  caller_email text := lower(coalesce(auth.jwt() ->> 'email', ''));
  snapshot_payload jsonb;
  anketa jsonb;
  status_row jsonb;
  existing_row public.client_publication_requests;
  result_row public.client_publication_requests;
begin
  if auth.role() <> 'authenticated' or caller_email = '' then
    raise exception 'AUTH_REQUIRED' using errcode = '42501';
  end if;
  if p_status_id is null or btrim(p_status_id) = '' then
    raise exception 'STATUS_REQUIRED' using errcode = '22023';
  end if;
  if p_requested_date is null
     or p_requested_date < current_date
     or p_requested_date > current_date + 180 then
    raise exception 'DATE_OUT_OF_RANGE' using errcode = '22023';
  end if;

  select payload into snapshot_payload
  from public.client_snapshots
  where email = caller_email;

  if snapshot_payload is null then
    raise exception 'SNAPSHOT_NOT_FOUND' using errcode = 'P0002';
  end if;

  select a.item, s.item
    into anketa, status_row
  from jsonb_array_elements(coalesce(snapshot_payload -> 'anketas', '[]'::jsonb)) a(item)
  cross join lateral jsonb_array_elements(coalesce(a.item -> 'statuses', '[]'::jsonb)) s(item)
  where s.item ->> 'id' = p_status_id
    and s.item ->> 'status' = '🏆 Выбран'
  limit 1;

  if status_row is null then
    raise exception 'STATUS_NOT_AVAILABLE' using errcode = '42501';
  end if;

  select * into existing_row
  from public.client_publication_requests
  where client_email = caller_email and status_id = p_status_id;

  if existing_row.id is not null
     and existing_row.request_status = 'accepted'
     and existing_row.status_date = (status_row ->> 'date')::date then
    raise exception 'DATE_ALREADY_ACCEPTED' using errcode = '23505';
  end if;

  insert into public.client_publication_requests (
    client_email, status_id, mentor_id, profile_id, status_date,
    anketa_code, anketa_name, account_name, requested_date,
    request_status, created_at, updated_at, resolved_at, resolved_by
  ) values (
    caller_email,
    p_status_id,
    status_row ->> 'mentorId',
    status_row ->> 'profileId',
    (status_row ->> 'date')::date,
    anketa ->> 'code',
    anketa ->> 'name',
    status_row ->> 'profileName',
    p_requested_date,
    'pending', now(), now(), null, null
  )
  on conflict (client_email, status_id) do update set
    mentor_id = excluded.mentor_id,
    profile_id = excluded.profile_id,
    status_date = excluded.status_date,
    anketa_code = excluded.anketa_code,
    anketa_name = excluded.anketa_name,
    account_name = excluded.account_name,
    requested_date = excluded.requested_date,
    request_status = 'pending',
    updated_at = now(),
    resolved_at = null,
    resolved_by = null
  returning * into result_row;

  return result_row;
end;
$$;

revoke all on function public.request_client_publication_date(text, date) from public;
grant execute on function public.request_client_publication_date(text, date) to authenticated;

create or replace function public.notify_owner_publication_request()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  owner_chat bigint := 6876234451;
  msg text;
begin
  if NEW.request_status <> 'pending' then return NEW; end if;
  if TG_OP = 'UPDATE'
     and OLD.request_status = 'pending'
     and OLD.requested_date = NEW.requested_date then
    return NEW;
  end if;

  msg := '📅 Клиент выбрал дату публикации' || E'\n'
      || '👤 ' || coalesce(NEW.anketa_code, '—') || ' · '
      || coalesce(NEW.anketa_name, NEW.client_email) || E'\n'
      || 'Аккаунт: ' || coalesce(NEW.account_name, '—') || E'\n'
      || 'Дата: ' || to_char(NEW.requested_date, 'DD.MM.YYYY') || E'\n'
      || 'Открой раздел «Задачи» для подтверждения.';

  insert into public.notification_outbox (
    telegram_chat_id, kind, message, status, mentor_id, profile_id, client_email
  ) values (
    owner_chat, 'client_publication_request', msg, 'pending',
    NEW.mentor_id, NEW.profile_id, NEW.client_email
  );
  return NEW;
end;
$$;

drop trigger if exists client_publication_requests_notify_trg
  on public.client_publication_requests;
create trigger client_publication_requests_notify_trg
  after insert or update of requested_date, request_status
  on public.client_publication_requests
  for each row execute function public.notify_owner_publication_request();

notify pgrst, 'reload schema';

commit;
