-- Track every Telegram review-text approval message by its exact chat/message
-- pair and remove it after the request is resolved in any client surface.
--
-- The delivery ledger is deliberately separate from notification_outbox:
-- notification rows are trimmed, while a delivered Telegram message must stay
-- addressable until it is either deleted or Telegram returns a final error.

begin;

create table if not exists public.client_telegram_message_deliveries (
  id bigint generated by default as identity primary key,
  outbox_id bigint,
  approval_request_id bigint not null,
  telegram_chat_id bigint not null,
  telegram_message_id bigint not null,
  delivery_kind text not null default 'client_text_approval',
  delivery_status text not null default 'active'
    check (delivery_status in ('active', 'delete_pending', 'deleted', 'compacted', 'delete_failed')),
  resolution_status text,
  delete_reason text,
  delete_attempts integer not null default 0 check (delete_attempts >= 0),
  last_error text,
  delivered_at timestamptz not null default now(),
  delivered_audit_at timestamptz,
  delete_queued_at timestamptz,
  deleted_at timestamptz,
  compacted_at timestamptz,
  updated_at timestamptz not null default now(),
  unique (telegram_chat_id, telegram_message_id)
);

create index if not exists client_telegram_message_deletions_pending_idx
  on public.client_telegram_message_deliveries (delivery_status, delete_queued_at, id)
  where delivery_status = 'delete_pending';

create index if not exists client_telegram_message_deliveries_approval_idx
  on public.client_telegram_message_deliveries (approval_request_id, id);

alter table public.client_telegram_message_deliveries enable row level security;
revoke all on public.client_telegram_message_deliveries from public, anon, authenticated;
grant all on public.client_telegram_message_deliveries to service_role;
grant usage, select on sequence public.client_telegram_message_deliveries_id_seq
  to service_role;

-- Called only by the notifier after Telegram sendMessage returns. It records
-- the Bot API result and closes the matching outbox row in one transaction.
-- If the client resolved the request while sendMessage was in flight, the
-- exact message is born in delete_pending state instead of being orphaned.
create or replace function public.record_client_text_approval_telegram_delivery(
  p_outbox_id bigint,
  p_telegram_chat_id bigint,
  p_telegram_message_id bigint
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_outbox public.notification_outbox;
  v_request_id bigint;
  v_request_status text;
  v_should_delete boolean;
  v_delivery public.client_telegram_message_deliveries;
begin
  if auth.role() <> 'service_role' then
    raise exception 'AUTH_REQUIRED' using errcode = '42501';
  end if;
  if coalesce(p_outbox_id, 0) <= 0
     or coalesce(p_telegram_chat_id, 0) = 0
     or coalesce(p_telegram_message_id, 0) <= 0 then
    raise exception 'INVALID_ARGUMENTS' using errcode = '22023';
  end if;

  select * into v_outbox
  from public.notification_outbox
  where id = p_outbox_id;

  if v_outbox.id is null
     or v_outbox.kind <> 'client_text_approval'
     or coalesce(v_outbox.action_ref, '') !~ '^[0-9]+$' then
    raise exception 'TEXT_APPROVAL_OUTBOX_NOT_FOUND' using errcode = 'P0002';
  end if;
  v_request_id := v_outbox.action_ref::bigint;
  select request_status into v_request_status
  from public.client_text_approval_requests
  where id = v_request_id
  for update;
  if not found then
    raise exception 'TEXT_APPROVAL_REQUEST_NOT_FOUND' using errcode = 'P0002';
  end if;

  -- Keep the lock order request -> outbox, matching all resolver RPCs. This
  -- makes the send/resolve race deterministic without creating a deadlock.
  select * into v_outbox
  from public.notification_outbox
  where id = p_outbox_id
  for update;
  if v_outbox.id is null
     or v_outbox.kind <> 'client_text_approval'
     or v_outbox.action_ref <> v_request_id::text then
    raise exception 'TEXT_APPROVAL_OUTBOX_CHANGED' using errcode = 'P0002';
  end if;
  if v_outbox.telegram_chat_id is distinct from p_telegram_chat_id then
    raise exception 'TELEGRAM_CHAT_MISMATCH' using errcode = '22023';
  end if;
  v_should_delete := v_request_status is distinct from 'pending';

  insert into public.client_telegram_message_deliveries as delivery (
    outbox_id, approval_request_id,
    telegram_chat_id, telegram_message_id,
    delivery_kind, delivery_status, resolution_status,
    delete_reason, delete_queued_at
  ) values (
    v_outbox.id, v_request_id,
    p_telegram_chat_id, p_telegram_message_id,
    'client_text_approval',
    case when v_should_delete then 'delete_pending' else 'active' end,
    case when v_should_delete then v_request_status else null end,
    case when v_should_delete then 'approval already resolved' else null end,
    case when v_should_delete then now() else null end
  )
  on conflict (telegram_chat_id, telegram_message_id) do update
  set outbox_id = excluded.outbox_id,
      approval_request_id = excluded.approval_request_id,
      resolution_status = case
        when v_should_delete then v_request_status
        else delivery.resolution_status
      end,
      delivery_status = case
        when delivery.delivery_status in ('deleted', 'compacted')
          then delivery.delivery_status
        when v_should_delete then 'delete_pending'
        else delivery.delivery_status
      end,
      delete_reason = case
        when v_should_delete then 'approval already resolved'
        else delivery.delete_reason
      end,
      delete_queued_at = case
        when v_should_delete
          then coalesce(delivery.delete_queued_at, now())
        else delivery.delete_queued_at
      end,
      updated_at = now()
  returning * into v_delivery;

  update public.notification_outbox
  set status = case
        when v_should_delete then 'skipped'
        else 'sent'
      end,
      sent_at = coalesce(sent_at, now()),
      last_error = case
        when v_should_delete then 'approval resolved; Telegram deletion queued'
        else null
      end
  where id = v_outbox.id;

  if v_delivery.delivered_audit_at is null then
    insert into public.client_telegram_audit (
      portal_email, member_id, event_name, actor, details
    )
    select request.portal_email,
           request.delivered_to_member_id,
           'text_approval_message_delivered',
           'telegram_notifier',
           jsonb_build_object(
             'request_id', v_request_id,
             'outbox_id', v_outbox.id,
             'delivery_id', v_delivery.id,
             'telegram_chat_id', p_telegram_chat_id,
             'telegram_message_id', p_telegram_message_id,
             'delete_queued', v_should_delete
           )
    from public.client_text_approval_requests request
    where request.id = v_request_id;

    update public.client_telegram_message_deliveries
    set delivered_audit_at = now(), updated_at = now()
    where id = v_delivery.id;
  end if;

  return jsonb_build_object(
    'ok', true,
    'delivery_id', v_delivery.id,
    'delivery_status', v_delivery.delivery_status
  );
end;
$$;

revoke all on function public.record_client_text_approval_telegram_delivery(bigint, bigint, bigint)
  from public, anon, authenticated;
grant execute on function public.record_client_text_approval_telegram_delivery(bigint, bigint, bigint)
  to service_role;

-- Every resolution path changes request_status: client portal, Telegram Mini
-- App, inline callback, or CRM cancellation. One trigger therefore keeps chat
-- cleanup consistent without duplicating logic across those RPC functions.
create or replace function public.queue_resolved_client_text_approval_message_deletions()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_count integer := 0;
begin
  if old.request_status = 'pending' and new.request_status <> 'pending' then
    update public.client_telegram_message_deliveries
    set delivery_status = 'delete_pending',
        resolution_status = new.request_status,
        delete_reason = 'approval resolved: ' || new.request_status,
        delete_queued_at = coalesce(delete_queued_at, now()),
        last_error = null,
        updated_at = now()
    where approval_request_id = new.id
      and delivery_kind = 'client_text_approval'
      and delivery_status in ('active', 'delete_failed');

    get diagnostics v_count = row_count;
    if v_count > 0 then
      insert into public.client_telegram_audit (
        portal_email, member_id, event_name, actor, details
      ) values (
        new.portal_email,
        new.resolved_by_member_id,
        'text_approval_message_delete_queued',
        coalesce(nullif(new.resolved_by_label, ''), 'system'),
        jsonb_build_object(
          'request_id', new.id,
          'request_status', new.request_status,
          'message_count', v_count
        )
      );
    end if;
  end if;
  return new;
end;
$$;

revoke all on function public.queue_resolved_client_text_approval_message_deletions()
  from public, anon, authenticated;

drop trigger if exists client_text_approval_message_delete_queue_trg
  on public.client_text_approval_requests;
create trigger client_text_approval_message_delete_queue_trg
  after update of request_status on public.client_text_approval_requests
  for each row
  execute function public.queue_resolved_client_text_approval_message_deletions();

-- The notifier reports each exact deleteMessage outcome through this RPC so
-- retries and final failures remain observable and idempotent.
create or replace function public.complete_client_telegram_message_deletion(
  p_delivery_id bigint,
  p_succeeded boolean,
  p_error text default null,
  p_final boolean default false,
  p_compacted boolean default false
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_delivery public.client_telegram_message_deliveries;
  v_event text;
begin
  if auth.role() <> 'service_role' then
    raise exception 'AUTH_REQUIRED' using errcode = '42501';
  end if;

  select * into v_delivery
  from public.client_telegram_message_deliveries
  where id = p_delivery_id
  for update;
  if v_delivery.id is null then
    return jsonb_build_object('ok', false, 'reason', 'DELIVERY_NOT_FOUND');
  end if;
  if v_delivery.delivery_status in ('deleted', 'compacted') then
    return jsonb_build_object('ok', true, 'delivery_status', v_delivery.delivery_status);
  end if;

  update public.client_telegram_message_deliveries
  set delivery_status = case
        when coalesce(p_succeeded, false) then 'deleted'
        when coalesce(p_compacted, false) then 'compacted'
        when coalesce(p_final, false) then 'delete_failed'
        else 'delete_pending'
      end,
      delete_attempts = delete_attempts + 1,
      last_error = case when coalesce(p_succeeded, false)
        then null else left(coalesce(p_error, 'unknown Telegram delete error'), 500) end,
      deleted_at = case when coalesce(p_succeeded, false) then now() else deleted_at end,
      compacted_at = case when coalesce(p_compacted, false) then now() else compacted_at end,
      updated_at = now()
  where id = v_delivery.id
  returning * into v_delivery;

  if coalesce(p_succeeded, false)
     or coalesce(p_compacted, false)
     or coalesce(p_final, false) then
    v_event := case
      when p_succeeded then 'text_approval_message_deleted'
      when p_compacted then 'text_approval_message_compacted'
      else 'text_approval_message_delete_failed'
    end;
    insert into public.client_telegram_audit (
      portal_email, member_id, event_name, actor, details
    )
    select request.portal_email,
           request.delivered_to_member_id,
           v_event,
           'telegram_notifier',
           jsonb_build_object(
             'request_id', v_delivery.approval_request_id,
             'delivery_id', v_delivery.id,
             'telegram_chat_id', v_delivery.telegram_chat_id,
             'telegram_message_id', v_delivery.telegram_message_id,
             'attempts', v_delivery.delete_attempts,
             'error', v_delivery.last_error
           )
    from public.client_text_approval_requests request
    where request.id = v_delivery.approval_request_id;
  end if;

  return jsonb_build_object(
    'ok', true,
    'delivery_status', v_delivery.delivery_status,
    'attempts', v_delivery.delete_attempts
  );
end;
$$;

revoke all on function public.complete_client_telegram_message_deletion(bigint, boolean, text, boolean, boolean)
  from public, anon, authenticated;
grant execute on function public.complete_client_telegram_message_deletion(bigint, boolean, text, boolean, boolean)
  to service_role;

notify pgrst, 'reload schema';

commit;
